// Package markdown renders report views as GitHub-flavored Markdown
// documents, the richest of the three output formats.
package markdown

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"pcapdigger/internal/report/model"
)

// WriteNetwork renders the network-engineering report.
func WriteNetwork(r *model.Report, outDir, baseName string) ([]string, error) {
	v := r.Network()
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Network Engineering Report — %s\n\n", v.Meta.SourceFile)
	fmt.Fprintf(&sb, "Generated by pcapdigger %s on %s.\n\n", v.Meta.ToolVersion, v.Meta.GeneratedAt.Format(time.RFC1123))

	sb.WriteString("## Capture Overview\n\n")
	writeKV(&sb, [][2]string{
		{"Source file", v.Meta.SourceFile},
		{"Link type", v.Meta.LinkType},
		{"First packet", fmtTime(v.Meta.FirstPacket)},
		{"Last packet", fmtTime(v.Meta.LastPacket)},
		{"Duration", fmt.Sprintf("%.1fs", v.Meta.DurationSecs)},
		{"Total packets", fmt.Sprintf("%d", v.Meta.TotalPackets)},
		{"Total bytes", fmt.Sprintf("%d", v.Meta.TotalBytes)},
	})

	if v.DiagramPath != "" {
		fmt.Fprintf(&sb, "\n## Flow Diagram\n\n![Network flow diagram](%s)\n\n", filepath.Base(v.DiagramPath))
	}

	sb.WriteString("\n## Protocol Mix\n\n")
	writeTable(&sb, []string{"Protocol", "Packets", "Bytes", "% of Bytes"}, mapRows(v.ProtocolMix, func(p model.ProtoStat) []string {
		return []string{p.Protocol, itoa(p.Packets), utoa(p.Bytes), pct(p.PctBytes)}
	}))

	sb.WriteString("\n## Application Protocol Mix\n\n")
	writeTable(&sb, []string{"Protocol", "Packets", "Bytes", "% of Bytes"}, mapRows(v.AppProtoMix, func(p model.ProtoStat) []string {
		return []string{p.Protocol, itoa(p.Packets), utoa(p.Bytes), pct(p.PctBytes)}
	}))

	sb.WriteString("\n## Top Talkers\n\n")
	writeTable(&sb, []string{"IP", "Hostnames", "Bytes (total)", "Packets (total)", "Country", "ASN Org"}, mapRows(v.TopTalkers, func(h model.Host) []string {
		return []string{h.IP, strings.Join(h.Hostnames, ", "), utoa(h.BytesOut + h.BytesIn), utoa(h.PacketsOut + h.PacketsIn), geoCountry(h), geoASOrg(h)}
	}))

	sb.WriteString("\n## Top Destination Ports\n\n")
	writeTable(&sb, []string{"Port", "Hosts"}, mapRows(v.TopPorts, func(p model.NameCountPort) []string {
		return []string{itoa(p.Port), itoa(p.Count)}
	}))

	sb.WriteString("\n## Host Inventory\n\n")
	writeTable(&sb, []string{"IP", "Hostnames", "Private", "Bytes Out", "Bytes In", "Ports Open", "Country", "ASN Org", "First Seen", "Last Seen"},
		mapRows(v.Hosts, func(h model.Host) []string {
			return []string{h.IP, strings.Join(h.Hostnames, ", "), yesNo(h.IsPrivate), utoa(h.BytesOut), utoa(h.BytesIn),
				intsToStr(h.PortsOpen), geoCountry(h), geoASOrg(h), fmtTime(h.FirstSeen), fmtTime(h.LastSeen)}
		}))

	sb.WriteString("\n## Conversations (Flows)\n\n")
	flows := v.Flows
	if len(flows) > 200 {
		flows = flows[:200]
		sb.WriteString("_Showing the 200 busiest conversations by bytes._\n\n")
	}
	writeTable(&sb, []string{"Proto", "App", "Host A", "Port A", "Host B", "Port B", "Bytes A→B", "Bytes B→A", "TLS", "SNI", "Decrypted"},
		mapRows(flows, func(f model.Flow) []string {
			decrypted := ""
			if f.TLSDecrypted {
				decrypted = "yes (" + f.TLSKeySource + ")"
			}
			return []string{f.Protocol, f.AppProto, f.HostA, itoa(f.PortA), f.HostB, itoa(f.PortB), utoa(f.BytesAB), utoa(f.BytesBA), f.TLSVer, f.TLSSNI, decrypted}
		}))

	sb.WriteString("\n## DNS Summary\n\n")
	writeKV(&sb, [][2]string{
		{"Total queries", itoa(v.DNS.TotalQueries)},
		{"Unique names", itoa(v.DNS.UniqueNames)},
		{"NXDOMAIN responses", itoa(v.DNS.NXDomainCount)},
	})
	if len(v.DNS.TopNames) > 0 {
		sb.WriteString("\n**Most-queried names:**\n\n")
		writeTable(&sb, []string{"Name", "Count"}, mapRows(v.DNS.TopNames, func(n model.NameCount) []string {
			return []string{n.Name, itoa(n.Count)}
		}))
	}

	sb.WriteString("\n## TLS Summary\n\n")
	writeKV(&sb, [][2]string{
		{"TLS handshakes observed", itoa(v.TLS.TotalHandshakes)},
		{"Weak cipher suites observed", itoa(v.TLS.WeakCount)},
	})
	if len(v.TLS.VersionCounts) > 0 {
		sb.WriteString("\n**Version breakdown:**\n\n")
		rows := [][]string{}
		for ver, count := range v.TLS.VersionCounts {
			rows = append(rows, []string{ver, itoa(count)})
		}
		writeTable(&sb, []string{"Version", "Count"}, rows)
	}

	if v.GeoIPNote != "" {
		fmt.Fprintf(&sb, "\n> **Note:** %s\n", v.GeoIPNote)
	}
	if v.WHOISNote != "" {
		fmt.Fprintf(&sb, "\n> **Note:** %s\n", v.WHOISNote)
	}
	if v.TLSNote != "" {
		fmt.Fprintf(&sb, "\n> **Note:** %s\n", v.TLSNote)
	}

	return write(outDir, baseName+"-network-report.md", sb.String())
}

// WriteSecurity renders the security-architect report.
func WriteSecurity(r *model.Report, outDir, baseName string) ([]string, error) {
	v := r.Security()
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Security Architect Report — %s\n\n", v.Meta.SourceFile)
	fmt.Fprintf(&sb, "Generated by pcapdigger %s on %s.\n\n", v.Meta.ToolVersion, v.Meta.GeneratedAt.Format(time.RFC1123))

	sb.WriteString("## Risk Summary\n\n")
	fmt.Fprintf(&sb, "**Overall risk: %s** (composite score %d/100)\n\n", v.Risk.OverallRisk, v.Risk.Score)
	writeTable(&sb, []string{"Severity", "Count"}, [][]string{
		{"Critical", itoa(v.Risk.CriticalCount)},
		{"High", itoa(v.Risk.HighCount)},
		{"Medium", itoa(v.Risk.MediumCount)},
		{"Low", itoa(v.Risk.LowCount)},
		{"Info", itoa(v.Risk.InfoCount)},
	})

	if v.DiagramPath != "" {
		fmt.Fprintf(&sb, "\n## Flow Diagram\n\n![Network flow diagram](%s)\n\n", filepath.Base(v.DiagramPath))
	}

	sb.WriteString("\n## Findings\n\n")
	if len(v.Findings) == 0 {
		sb.WriteString("No findings were raised by the built-in detectors for this capture.\n")
	}
	for _, f := range v.Findings {
		fmt.Fprintf(&sb, "### [%s] %s\n\n", f.Severity, f.Title)
		fmt.Fprintf(&sb, "- **Category:** %s\n", f.Category)
		if len(f.Hosts) > 0 {
			fmt.Fprintf(&sb, "- **Hosts involved:** %s\n", strings.Join(f.Hosts, ", "))
		}
		if !f.FirstSeen.IsZero() {
			fmt.Fprintf(&sb, "- **Observed:** %s – %s\n", fmtTime(f.FirstSeen), fmtTime(f.LastSeen))
		}
		fmt.Fprintf(&sb, "\n%s\n\n", f.Description)
		if len(f.Evidence) > 0 {
			sb.WriteString("**Evidence:**\n\n")
			for _, e := range f.Evidence {
				fmt.Fprintf(&sb, "- `%s`\n", e)
			}
			sb.WriteString("\n")
		}
		fmt.Fprintf(&sb, "**Recommendation:** %s\n\n---\n\n", f.Recommendation)
	}

	sb.WriteString("## Hosts Involved in Findings\n\n")
	writeTable(&sb, []string{"IP", "Hostnames", "Private", "Country", "ASN Org", "WHOIS Org", "Finding IDs"},
		mapRows(v.FlaggedHosts, func(h model.Host) []string {
			whoisOrg := ""
			if h.WHOIS != nil {
				whoisOrg = h.WHOIS.Organization
			}
			return []string{h.IP, strings.Join(h.Hostnames, ", "), yesNo(h.IsPrivate), geoCountry(h), geoASOrg(h), whoisOrg, intsToStr(h.FindingIDs)}
		}))

	if v.WHOISNote != "" {
		fmt.Fprintf(&sb, "\n> **Note:** %s\n", v.WHOISNote)
	}
	if v.TLSNote != "" {
		fmt.Fprintf(&sb, "\n> **Note:** %s\n", v.TLSNote)
	}

	return write(outDir, baseName+"-security-report.md", sb.String())
}

// WriteExecutive renders the executive report.
func WriteExecutive(r *model.Report, outDir, baseName string) ([]string, error) {
	v := r.Executive()
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Executive Summary — %s\n\n", v.SourceFile)
	fmt.Fprintf(&sb, "_Generated %s._\n\n", v.GeneratedAt.Format("January 2, 2006"))

	fmt.Fprintf(&sb, "## Overall Risk: %s\n\n", v.Risk.OverallRisk)

	sb.WriteString("### Key Points\n\n")
	for _, h := range v.Highlights {
		fmt.Fprintf(&sb, "- %s\n", h)
	}

	if len(v.TopFindings) > 0 {
		sb.WriteString("\n### Top Issues\n\n")
		for _, f := range v.TopFindings {
			fmt.Fprintf(&sb, "- **[%s] %s** — %s\n", f.Severity, f.Title, plainLanguage(f.Description))
		}
	} else {
		sb.WriteString("\nNo significant security issues were identified in this capture.\n")
	}

	sb.WriteString("\n### What This Means\n\n")
	sb.WriteString(riskNarrative(v.Risk.OverallRisk))

	return write(outDir, baseName+"-executive-report.md", sb.String())
}

func riskNarrative(overall string) string {
	switch overall {
	case "Critical":
		return "One or more critical issues were found that likely represent active compromise or severe exposure. Immediate incident response and remediation is recommended.\n"
	case "High":
		return "Significant security weaknesses were identified that materially increase risk. Prompt remediation is recommended.\n"
	case "Medium":
		return "Some notable weaknesses were identified. These should be scheduled for remediation as part of routine security hardening.\n"
	case "Low":
		return "Minor issues were identified with limited business impact. Address opportunistically.\n"
	default:
		return "No significant issues were identified in this capture based on the built-in analysis.\n"
	}
}

// plainLanguage trims a technical finding description down to its first
// sentence, for the executive audience.
func plainLanguage(desc string) string {
	if idx := strings.Index(desc, ". "); idx != -1 {
		return desc[:idx+1]
	}
	return desc
}

func write(outDir, fileName, content string) ([]string, error) {
	path := filepath.Join(outDir, fileName)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", path, err)
	}
	return []string{path}, nil
}

func writeKV(sb *strings.Builder, kv [][2]string) {
	for _, p := range kv {
		fmt.Fprintf(sb, "- **%s:** %s\n", p[0], p[1])
	}
}

func writeTable(sb *strings.Builder, headers []string, rows [][]string) {
	if len(rows) == 0 {
		sb.WriteString("_No data._\n")
		return
	}
	sb.WriteString("| " + strings.Join(headers, " | ") + " |\n")
	sb.WriteString("|" + strings.Repeat(" --- |", len(headers)) + "\n")
	for _, row := range rows {
		escaped := make([]string, len(row))
		for i, c := range row {
			escaped[i] = strings.ReplaceAll(c, "|", "\\|")
		}
		sb.WriteString("| " + strings.Join(escaped, " | ") + " |\n")
	}
}

func mapRows[T any](items []T, fn func(T) []string) [][]string {
	rows := make([][]string, 0, len(items))
	for _, it := range items {
		rows = append(rows, fn(it))
	}
	return rows
}

func geoCountry(h model.Host) string {
	if h.Geo != nil {
		return h.Geo.Country
	}
	return ""
}

func geoASOrg(h model.Host) string {
	if h.Geo != nil {
		return h.Geo.ASOrg
	}
	return ""
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func itoa(n int) string    { return fmt.Sprintf("%d", n) }
func utoa(n uint64) string { return fmt.Sprintf("%d", n) }
func pct(f float64) string { return fmt.Sprintf("%.1f%%", f) }
func fmtTime(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.UTC().Format(time.RFC3339)
}

func intsToStr(vals []int) string {
	parts := make([]string, 0, len(vals))
	for _, v := range vals {
		parts = append(parts, itoa(v))
	}
	return strings.Join(parts, ", ")
}
